server:
  port: 8081
spring:
  application:
    name: lagou-server-resume
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #避免将驼峰命名转换为下划线命名
# 注册到eureka 服务中心
eureka:
  client:
    service-url:
      #注册到集群，就把多个eureka服务地址使用逗号隔开。
      defaultZone: http://www.xfr.com:8762/eureka,http://www.eran.com:8761/eureka
    #每隔多久获取服务中心的列表
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true #服务实例中显示ip，而不是显示主机名（主要是为了兼容老版本的eureka）
    #自定义实例名称
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
    #租约续约时间间隔，默认30秒（心跳机制）
    lease-renewal-interval-in-seconds: 30
    #租约到期，服务时效时间，默认值90秒，服务超过90秒没有发生心跳，eureka server 会将服务从列表移除
    lease-expiration-duration-in-seconds: 90
    #自定义元数据
    metadata-map:
      x-name: inner-peace
      x-age: 23
      x-sex: 男